---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: share
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ChristopherJMiller/luma-homeops.git
    path: cluster/share
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
