---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-migration
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ChristopherJMiller/luma-homeops.git
    path: cluster/traefik-migration
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
