---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: royaltracker-db
  namespace: royaltracker
spec:
  encryptedData:
    database_url: AgDAL7WSSVK4UWsg5ojiqBpTofrTcB2747u2K/JwjQ6yiBUk8BgPnoYG5NsDyvKenGBmmgeRMT7UpADWZF5dgdoOsUZzgMRSHKC4GIPL826ZPMIFtZAY8jat8YVtznjMyquFHLAfp/jfcu+ncHc66eAVmO0XJO8RuTE4UeLVmXFbyFnJdI5F3lFqNZaPOWbWcoDgduKwfU+8ybMyYYjDYLFHm2JNYObhIeJYo9AKgAHwj7dZqxlP+3Ja2XjXoEsQZFLewocSV2aW0/P5bZNItdn9sjFt6Pox/n4OPSNkCOSfXBnKfzwp9E0LgAEnOIMoFkq+oOoB5WpyMAQusRmVTG/5lSFkswI5sW9vdGLoUZ9RdvAe7kKG+g1dbxHgR2UshLpTPhfiQtOk08nF3vltxgaEGugKm6ucfP8CjOtaRb1juBdYkkbAULZjXt5Iu+MLfz6lWAmAtGJFBywA3KeI/vDdIBQc9v5Eld8zKGnR+RAdfzXzSwUR+uMDzHFaRSXH0aDtfZ0WIe1Ed9X6YVml//C1jfH6juRLVRQ/MfcgrP9dvViA26aVbKem8TWwX8KANDHbbEdylRroBe2w+qQDxVCBYKv0F5R0OE1gOFv1RVp95T5s/4H+3CAN4CeWEfhR6IqdQ+u+hcyyPESeVxglJJsn+GebPOM1eOj4527JAThusK7YiVstpEYaw9iaRpIqpUvrRQ3WCr/DzOk0PmBjQW/ACaUsJ3OpupEiv9vf7ioefkGA4f7o1m6K2/mDPX4fHANeIep80bK6nE9fVe/b+3jbalOO2Un9ayeyLe/lYbER2Mb+00+rLnOgx5/WkQ4KyR6I9ezofid0XGV5Rr+YSlwSZpLxI81kIOZ7XIJ/nwLY23xm151b8tV35NlPCYfwR6qBRf2aAKQ91SVuWIWp5v/4Qblf5tDjs+buLzk=
  template:
    metadata:
      name: royaltracker-db
      namespace: royaltracker
    type: Opaque
