---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: royaltracker
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAolqpEr2rKhvd1CyNiB5ziO4of7Xv3+nIX4rt0GXFYcOFWXxT6PxQ7aRkA74osaVPEC2CeqoGf78ujfPm6hhj8knGPFWlpK+pox9J8LGrEQyUbdGX8Jb7aT/JRfD40+3gTz5JYtkpXQE5pI1OYa3rXBF6MKinW+71BM3JPGgWzjdZsCWlmvmXpv7CmfOWOEikIMPQgb/SDRYOhnQFqtYOyXOFWGv+TWjMwYyB0MOFguX2AbhewhnbY6LUl9rzg8gG+qcEvfQOsFjtYwBj8lD5D1jjD6iF2zR9vHmWQLeUHK7128JUr7MCV7/dZ6g+zIz5R6bsg7Ky6kNUJXYfPX8j+sv+ravSF/oF9WqJzI+s6LjTYpwxATdqDughY4vBk9skMX6wXo7xJ+1xRQwbfW1H1Ujq+d3hCms19MtOw7oZH82KkAE+ciIYr4ajy5nLJXR94NJsL7VzqagBDgao/wBs+UhHzOdv6oDgUeTESaTzQjmKHGXjmr+S3tM/rPcbS3Xwomy9+VG3eoiwerYfoPd8JsDr0wGlT7fkSoqAxzBAELp0MIXFff+1y+V0EhrjCEb3Ewv9u1bTUmOVzdbgtBLSVwxzTnxvNuvh+naUSlPuxCq6sUcHr86PNwu7lMVPFaqMjGLAE5WDFXJcx+CY+cJ2gv5zch6MR9OmEGiZPiu2/gL+7RrHhA3l56epzOlSKNcdf+pLooW0MDx1T3HtUViDZ8HxdxjhNDHiK
    AWS_SECRET_ACCESS_KEY: AgACNW8CmfIqvo9p6o715lgf4o8hPWdfERgg7dNUnGDPy21IZJR/kk5Nn+BtIpdVfaMOU0AFL5AMUL666RTSW9Dt4Qdpf1f56Zqt4W71XwtFfollzQClXCXkrJxmYuKNHimCuIFxtYZDX+bTMwOgQgbQ16hM08cwMhav5tS2P4u2YG8aoPAQmAFzepy8cGRGpqWjybAV5NnD0/slLWADGp+UUX/6mklDDVFJDzG4abb7J2OFmElRNhbGeNSrc03Dx65gLtRiVCWQUs/AicNvrwU3fVp4kGXU4Ew6m1w5tNu7oluLZh5LBrV3yT9vYOYajxVq/PubKpLyX33kW3aSAboQq30xjWvWCoQjZ3ZnRcGN4qyP61kQ5Ryc4Tm+PnLvapidz1/pbZXYTrrJnIa7N03Nf8OyQobuhbOH0I4H3Z2wxxEsP2tKir/ArMm+Jf7RO5mqLsZlC/m359pEI/YXxcdPS2md/TfxQWLYcZAZ6iWM0aLwMRfFskn4uDAc9XB6bQC7+OVfEt5JKlvJonqOWp1JqneJVAm5K3tHWTWMh3tkY+so084hXkAv9NAh6pvM4Ehs2OAr6qxx/yz2wkRNeNeJA9e4McSTIWLz3WtJVqk6hGeb5DS/wlZpeUb5rC4U1taxMWGuz8yOfw4gItepd8CmFFnOV8r3dHeNaHKkRMnaC7eLXrg9zJdAgin+xr7Ec2gsJG/btQuByPaE+Cht2PjNjoOTdF+LchXlOIaHjlqH
  template:
    metadata:
      name: logical-backup-s3
      namespace: royaltracker
