---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-metrics-token
  namespace: prometheus
spec:
  encryptedData:
    token: AgAlmJWviTpkrNr3tpxEpVK4vGY3IMARKTRT1vE79GCTMolINCu2HOKuoqInkGyzD2s5hq/q4aVvcbjU3nxcEnUbSz7rhAh1kUkSTs1X2Y+gGxqt/CigzDHtH+88oEQ6Eg+6m/f6euEWMWGBlmCoRvGoH7EB+IAphcu5je5jSeVwOuVPtFzNZZ4E1ue070l5YzEFTLDgGSdm2XrBPMDuP5u/s1YgP8k2iFO9DwMJIkDN7FcRHU4BqowQzU1TUM8FYF9IpjsDFsgnDLf/Bek4XYU0XniGsZJZH3IQyBONZ1os8sGKo/spEeFwmu6cl/yfrmwWW8D2vOPEeT4BYRYZ8PMJfV5X4b996WMQih0drcwraRXbo44pEGJWzhl+tieYM2JYpnca3rsBBDZyFVZMep0kfmHaIuao7r2Z/DvQeXDcKSeN6AC7p4ImB7jMk63KZ2NwiIjRG5eUSe7VuT3scXTvFDK5UGQgehrL0sxOW0XY64UPt9FdtFxz08ELxhlVyjWblMbWxyD8Purf8babIpCSeRs8qI3rTikLTXiSaIz/Ns2GNXHJftKcV1T8CUt5rCws7pUeC/KRbks8txX4yCureYOq4vyV9pdDQ9VaE45myWMKqODTLEx0/XDhOwTyRKwVYa2WVQfMQpo5kipi4iYbLE17CT3ZOcM2Xn0eY+H6BDjnw47BocoFql3ob1QeCaRgu6Z7Eu7VFPBWfmLuesdw0ZY3z6wluvSB1mBN7emuDtRvitntC8MRNqFuhV+ruiZcKi3E60YWuoA/UF2KMpMaaey0MqBXlQZ5bpTYzlypqjNdJxNhIyvCzaFW9tUyEYspxN47DpQXUNlk6ymyIeOAph6phh8++ZvqLXnSjajGtdNN1ZGMccGJ+WFk9jSzgDhZBBwttZcM3Bjp2ReD7aVqjnUmyf/QFCu87MTm+pMvJ/ZJrctjWKYm
  template:
    metadata:
      name: ha-metrics-token
      namespace: prometheus
