---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-metrics-token
  namespace: prometheus
spec:
  encryptedData:
    token: AgAVqiLbJb+q2OlqUIVRn3XC88QylL8qGuOfHDPKh9z/1Uf0sVOALk1On//6lbuarje1PryGTESDdF+vIAt0KmOvbluTPmCm+8XNnKegX6ukRBAZEjfz2PDfSGDjdfASEYpBemu9pNwVHSQzpc+eKyAahdotr96jUJtvWUenDJJNhierBh1XZZ8WR+6zs/a4RlLfQCIGcBQILoYie6elBSGChdjHDEMWKUmIaYu1bNpVcIa5rCaLATgXqnI/tKVvlM2SBUAW0MMUkInkL/3+ffvoEG+ik/UWg86P0YTZWZJpZ9f2pkbm7M5vskl7/58owK2q52r5eN+biOfEtBaqVufm1yFm6Lf0Wqps/T+Sxooxdqk/iqUGGLGbZSD1PfzsI8aLtd0IWUXnYnUUu0b2dAKm7Zukjf5obYlwOTu+2M4UM5XL3bHnzWNtevwBFmyvbXIwQ2jgaXBro6XRbP0wK+jOGxpfLp7vdUz4G/5EhSL1Aqz/VwOAzMVMfWcBbqE4HuL4NAlO6+5ma4dr+8sEk7UE5dRQDmMTDJaukKkpbeRUO4oVWICvnNVl92a7H5gNSthvGogzWSVsoakvjSbRHRyJsCKO4rGd6Q9h/chhWgAo089TWYTdOOH9IzEeCRrgBEtOD+QYTYUMl3FWYepF/bkiXS4v56TynWsfdzt2s6wwDAiM3rhRecv4Hqm1utF4NTnNdplNmOUxMLqnEYEqx6xviZb3/gH53uXWlhZZY139ljezSUD+mxpvfKIbrqnuxd4JxTPVuB/ym2jVrfU6I1q0dlQFJcV1IphJ9sk9gmHFMS7eEU5aCozbQgLI1n4JAnpdaJnvbhuJtrRQC0rTMPAtRsOfzeZeMXLPJwzZeFFV98zsbTVqXxilY2FMF+Y9O79dyb7YsfXHy5Z5fN5kcR1RV9QHGh+s2eaRXJKL0qJwJf0h6ixvQDI=
  template:
    metadata:
      name: ha-metrics-token
      namespace: prometheus
