---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-reload-token
  namespace: home-assistant
spec:
  encryptedData:
    token: AgCS9r1891gaiA7Xyi6rNKm4De70IjYLlbQI3driX30bWGY2HKanKpGFYp6/m4Pk5Jn/HBfiYD3pgGHMrCrNPwDMbxkTu8CpCL1NhuABBQsabC6Il8ZTbmiS0cbJAISIWsLSU9ga4KGUMbDNsbJrgKIhbRfhdhuW9tISyc8fWpXBSdUX1NVfXaYDn37ZgK91hQJL7BL+fZC3Ups/T3NcipXNMifpWrqyBUjO2Vj8i2SrNqk/Cv98XUEpEmlN6woqa4Z5AAIExFP++fSvIpFzOtXbB48QkSq2xUEW2QI1KpZyk2mQFrzvzcNqYgOekW5exmnDxE1oRFh5S9p9NgdeiZMA2I6I1cIeQnw4zTItIObVNHi851q532nYA+Nuh9hmBMzvYRhLF9XedVunmHmUYuJoLS5HiRFRK88khhht859clSsQkKWHoKF6mrg4S226y+ENx07FQnilosl4V5GwTMrIoxY0TNdUmjdrohSlJQc8XQ+C6StNnXFraiYvHzWhbrFRZgJAlxe2sDbblZ7+lHS1qk0R47Y0Z5SMLsQ7kQhezKyZP4CSLjQIn6e2i+gb+e6/g9tde8TgT7M03FsS7bir991jWaHBLs4BN4Vo+1mDmTI1h/jWJihI4vHerH60Jfl7i6hLHRR/P2ZpVP3/f2Z8fiAFxoWQyTi7h98qMFNCS1xKVFrCOz7tYwzX4gz4IKgVmrY9XI7XYuDtIL3PSRr+Ns5XgTBJP0M1/A/5dlHS+OcmsONU6lobEVKKuxu5ErWhGO+34WIvEiyCU8B0qTLzxAA97GoIYRXtGTAwocimHVEb4K1RfDbsp4NEU4as+QLjLF0CyvZQYGaghqhDXClqC0hjehc44s36ZdjgfvKY9Myl1GYSfiorkUu10HjNRe05JX3QBNPLmxZ62oSgxr5MSZli/T5AUsvyOczGaRVOPJKvgvnomhu+
  template:
    metadata:
      name: ha-reload-token
      namespace: home-assistant
