---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-secrets
  namespace: home-assistant
spec:
  encryptedData:
    secrets.yaml: AgAID0fR/3l+j4ylarydx66Ujf/WoRO+NwI3KGxFIz2H5s+LEKrkcwAoOSFGlu5uq68Cgjl7ojcvIXSDdPFjl7u9HUPjW1bumCaueNCkHVQXKCDGst0yanyssHf5hK5z53lu8oq1HXlCSo+iq0am5B6jy/AsO7coUSjBc8p3Zu3beXfuoT3taDTkLKYXDvoi0owVADyVy58hptPPqZcRMOs2JlqzKg6aleW6u3kJzyoQtmL4lJwSiSKtUSdFFFTGIZhFdlbyrUr0cKB9NX9QhCuUXdHEhvKilmsPG4eWY+//a5izeIfL0c//cvQLryWaFvMzGctmUZMuRqR/1Iq1MWQnkoBsDl6Skh0KOJrRVE9S/IWRZyTAdiISYNNMk2IawQTGOXP9HOkJN6RlX8aRNSSOXV3rEtAKSNt+HjMAIxr9FQZKV6ePbQl7xuEAytZDm+xI6N2loP9uL0QUCzjv8vJWg1/1FCIAngMEOs+jgGPoTjzmekQUrDiYzR+e3jMEsWKOTh0cD1DUAmTLHuByAY4e+JhL5FSFE06IVscdzxOA0zzmztzToeeEJQxP6LkJQmF9lfLYtVOhnWWGc5mSX0IYDSND6MBgIwfNTXOn/bw8mD2tKQlwKqAxpRCMfd/3FTujK+gYJDVzOQLSsk9vHedQt/2j3vHbv46CQ5DSusyb/+KOAgm2RUB/b2tZsvFYRhgFsydeF3B6tiZ8LnM58WoInoQESCxs3zYK
  template:
    metadata:
      name: ha-secrets
      namespace: home-assistant
    type: Opaque
