---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: home-assistant
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAR02gB06v8vpOG3jiUBjyb5Ih426TGUSfTkgCL7hxKia7AItimCJhkPDlwsOHsYrsVadqomYXy7tCra4WIf0R0Pw9rkQPzGXRRhqJnGSQxhGH7FotNgpRUq0cRXWf/OaolMsOSn3n3+O/yRD/f0wd7gS6Iukj8VvRzbBfYEDtH+DUpAbYbzfUFuIDoS5Yrw9fC9F6A8gn+ONsnoxZGSwqhcx+zC0NuknPrQ2bCNxZEdTBKXjl7wuFWQpaQCovs+gz/FVHCHMSVlLtzZK6LZiMA5xClIqjduaoKi9Y8c+GCcDNjXUDDe+xItlJgJC5zKbMWnWKd9zZf9IZcK9/k0gvCM/f1+RPfQooP6mYzrEGezPtcmG3ApXnVzquLfN0RvNWJ/9T5q2n/sDV6/keI+upa0s737aHiJqzHU+NZub1aJ+z+LsleSkA3zR76ncrOR+2Jq17KRu5YR9vOTx1TKrwpykJRj7W1jJa97RGYMtDa9DND2TYjB139/g6tjFzZ8WxS7ryBrRTFo2iAXkVB62iEp3kwZJq7vdciKRw7ox5X7VM0zCkBIMvWuBU+ttbSVFmPOahoOtxIRX5d39+WToaP5GF9hEHS2HsMnwlmbqi8sxUicoMb1IS6Hfoeql6o8W0MvCuuWi3tVCG/kYuHz3TtSCvboCmi3ehqV+nAsd48ocvZblqn3xV1slpyQQJCkNxM7HoI5mqzPzctkt0l4tqNfTpjdzlJBeNn
    AWS_SECRET_ACCESS_KEY: AgBIUCI2S9ukLEOBhsNwgdAwnn4ejbA6WZIZa0njIDS7x79wY/zaDKFrgIu3tz56e27aKNbrC3eYc3ctKdmYGPKbDLVo0pc6G+sOFdnK/fVroYNoKxCHndnvSz6WnlQyH0p4NkXZOFIwWuj62uMhbz+JVG8lMAPPcs6Ok2jUTqhgur/WmanJ1wd7dstdN2bp4LjTYErF+1zzLx7gZ7v1zVnTfQh449io1T4YwwWfKm2D+FmMv4T8QM+DJrKe633UMxRD/RTMcANhpK+64vRaL0DVjvgHCa0YcosSO2f9tmW9A2FgGd7tXbANoShV14RRLKw4U3F7go5vbCiqaNFekkkEFfuXVqQNXy38J/zES9HU1FYRNgrqnr6CMj0zz8XLrRI7GYGkXzILvzUUxXgFINompH2FKZd7SMYBLzK5QoH+OO3vt8Id/3f9EDxWTEfirFTAb3DB/uWIjGMQ7msS8ynAAiAW1QeOuoSyvgqKeM8s/Ubm5W+y8Jr6i4TmrKqEfSNIuooHfl+0+hUBw+oOLoHXGHthd5FCNsD5jCJC9KeP7WHGks1cbeT1KO+P3eaVK6+tLrBi5TiyRiJQjTGTOBz1L8BqjgUoQWDwxIgrreoy3AlTkfe07xoH7DAxVVohJS7Bhwm50z9vDjRzDn3OSRMmKEGZskvb42AzQJsoztW9dGY7gZ5ZDv6SKuNFjuZiFVPYlXxAM8dnlRDn3v4Sf7PK5pvPTAdDrrnyLqaBAL9H
  template:
    metadata:
      name: logical-backup-s3
      namespace: home-assistant
