---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-family-emails
  namespace: oauth2-proxy
spec:
  encryptedData:
    emails: AgBfHxmZdaMLeLlR81FGX9xD9TYqqS5K33jpHJWR+qxB9HLHY6WXnmtfHhmHunyFUtN8R7+eCu8DjMgzoyA4elaxd357AD4YJCeNayzGyH29uLi4aj/kN8utOZMekjRHMWXT7xbTq0bfHuH468/UGl9xS5ludLjwkfnMMgZ71Qb/qIG4JEAiJTrcIAKRXpEOfTOzfPlfgclZZ9nj61jb54QKIzIFu3xCl/mPAJlBgS3BZxDyQG2ipkIPwRLCV5zhwcgKa8dIzylCb3B7TpPDlzMovE9mJhJ1+/wlMOICx0wFUfYEBXq49NmuMy9CEBdK4ZQB2BQbOqrCe+PJBLrQmlw3rTjCrpH58I1DAjT/VeGiqS3+8Vgq/sC29jqXBlws4vlshQYjNi8do1QyFPOOiHO4EgEQhgs0Ko1+KcMI05SHups8ghP9yAgt4RwHSWlcTXq7Bo4r4eh9PCYxlQVP/8p09Zdo61mBxA5pOeQC/vm7vKGftME6WpuwjdoCoC8+9rbVXsrWZWlHyVNxtAN5oMdOh3kvhCbuB4pIxYalMWWMAE+O6xV50hzmTmhgA5UZhmtEQUElrQC6xGj/73jcIRtFHw11viCQQ54bOg0QTOxCJDagtjK1/ebjceWl4Z75UPZ1LERgw+I5eelZHCW6Ryqilo4Lniclzu1uoQjZ10b5oA43HCJAAkbJoWDpQNgoUMpU5EFWo47zrNKBIm76IBgweI2CMZyp9awg8Dsvz7A50Lq47AnldDx1ZAp2LUc1o6ZpCdlit/AdCY8ntXKU8LYRYWQx9/qWrCDoVpFwWmisxnRtgFUKGqliw3znqisOSRfxpO+H6Mk83n0=
  template:
    metadata:
      name: oauth2-proxy-family-emails
      namespace: oauth2-proxy
