---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - namespace.yaml
  - google-oauth.yaml
  - emails-admin.yaml
  - emails-family.yaml
  - admin.yaml
  - family.yaml
  - middlewares.yaml
  - servicemonitors.yaml
