---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: attic-db
  namespace: attic
spec:
  encryptedData:
    database_url: AgBF5b59jFEaXeFGJmUWFO5xydN4ZPD34h4VjQaJ1WbBgFw4MSenkmQTUtvovLWBLoJ+CaVcmim3zakjs8DJRJ4Ohblq9VNknTeZQecP2OgjaUFAY/XSlOYk2K4YoQ3f4CcfDHOempbD0Q3cdf+sGXe6ErQ33uju1Q1szEV9/yDfIsukfNEe5f0dUgZHhLLa/esBDh1nBItpx5Ccrzzql95VAoYD5bMe9SclhUgUgymUjNr8jabc5bYdefoGDHunq2BOnJzgswv7qh/teohOJf3zfqeRUNbGOzBWfZ0PqTFd0vgwr4J/I/r14hQPf5UmjIQSm/K5JAwDtjx2CNXoCvJOeKwwwqAXWgtbBYIPXA58/OEC0ha8O3K0qzy84sodfBxkX8/+mGPO1bURS5AZbmymp8Oa3ptbjAq2H8BkJVuzfz60KZcDc8KGgwfvOWs0fhUE0H85mNYkIBJVXE1f0bVWZSzAMKraTgG1bDSa3bjXRrR7oKY1A59HHibb188Pwxrp9zqP5NB4KVBTcb+4XdzxeQpm3nQsMsBkpJoTuzIdKh8CHQETJ/HKfaIuqRp/Lz7+s7LM4xqJjAS2iAP2+1vTUTUGiIyG6ZbJUvigV+36QE6Wu/uAq5zwEk225s0jviiywtXpGprQonY8s+rkgRDZqGrawyhR/ssHa+syJ+NjwZR1+tEGV2EF3DYju9Iacgk8cXVmdpTkyOt2/mB/vHqFCcePzNah+w3tv7mJHDesw699Lft96u+/YlnZKYdOeVyt2BmezujaFOHFSQxS0FayHTQbLDH3XH8LJtBocWki/mzA7dGTVyX5q63INtZMIQ3HEMgk/wu1Rcd9ZdeKJ1/QOGad4nvljfTjQTXkggG1ytbOwi1y1LYabfkmFg2CJA==
  template:
    metadata:
      name: attic-db
      namespace: attic
    type: Opaque
