---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: attic
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA51bk02A+b3TdILKLP93ubFIM9B0olpfzCiwHOBKRVogdlbpsO8axGtmbwoDRQ5/pzwZii4QHD3ZManaR4XBeli2DoiQrb0pHtDJMn0yE+mg+KP41sxd43cOU9M0uYizvxaWgPFSlRTZwmHj9ZYs4PD2GkBiG4P6CI4cyhEkL40NCLG60Qnh/1EWG6gBV09qugFpuIKYNAUMNyU0d+5OLhLYO28hIzmr0fSbuHN4UA3mdmh21RQrw0KZJ0eIj108jzSDxFJMQ3h8yADUqAZ+gsWZj8TSTdE4e7xiuXBjvpEtYnDkV/u+wXxHNDDVXMFeUe/IRenzPvGfQsPuEZ5VWYy6BTcDYo+sqrfg7IoYvsMZAyqvPDXlko45vu1fm03thiw5gJvaGJA4loAx82EF5/oi8Ig9I50tWwcQwOz+L5UGfDQVzanfkzxbdyO6m9y0RvC/6nmQlk4hOWczjTz47fMtWPs/lLRdpUmiOu8U0LPHYtY9+aMumFV2s7bm7ZARB3uyTsPVYgSi2BxkTMP9plqbtHsSzK5+4k501Cf8PP1IxrVyJC7JeXh4O+K7m1dp6OBLOTWVXpnXrMIEAIBVdSlOTHJj2kSwEz2BZkA4U7NZma8mUiZBFgihsspcFNVjmRQFnYD9LAI0I2CVlItwqcjAiLHfOwmQv1sRvBM2ZSjfrheD349AuLIBq+lHNG+9dOrhSNQBXECBS3T5J0mWJdnm3ckvSk8hPy
    AWS_SECRET_ACCESS_KEY: AgAD3Zb0KRxtCGbQB9WIk1AEVC9zd+es68QOO23dAbDULWoth2pfePo2rxTmZ/m4oEF9ucekQwczyXAnN7AbO+NWGAe4MDRgn2gfRTDJeHbNxOIWBQE/9BXmALtYg+6lj+2HYURQYCttdWgdIb2S36DJaQf3oJMf7SgEda8ANfykkzFiYeVF6SRLEFhYLSyJYL7e7bFAGjiSb0elA81CGvt+a2Qg/wt0LQZ+/H9ffZh+MkvyGIEo68Qcz420GX4WTVVWxW5rOCQ8zBTjko6G6kCST390TVEFS+T7dXfu8aWaAJpiDvHZ+ttgbi2miV9S07IAvoexuZEVwh0BDwIT6KaQpWm76vqDELXTbxEZMzNQHTtCi3SnPXmgFHjZbnGyPAROj4l4WdJWQ1YYbAByNRVrR9duN3ByTcDB5mbZaJGu3Hbz/RXvH96Dt4ugHdmPeUpeCe0XyiKOlddiuA7flH0s5VlMAAt58h+RW/t6v8GqdAv+DrS2jeMuFVVVpITTeP0XJANxyR+ZWoqtb0gfIZL0aykqe2qkEcGUl7pO7BK3nmCjGp/bgj3htgf//M58ZOj4qQC7HsoqlMNNYPYy5CW2XtlOXEauDIeawT/6MGv41Wi6MzFKjfJTptNa5ljlUnqrLgcv5l4x8J32CWOko23MZbPM5065Iw6BW0zl0dnJyOF7R9DPnMzhdeV6ulSk7ze4GA0QLQIjO3LaQq7T4P+9C5urYslIPQlNfhwj/fcb
  template:
    metadata:
      name: logical-backup-s3
      namespace: attic
