---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: immich
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAtpHHy7YTKeWR5WwnymcKVa6GzgV2oojxk2TWMwx8OwG2xgfSjPXPcs300kSs7YQyJZ5KwGfK0E2MbQzDmGDMXRIGsQnYJ1GVTN2wx1cbk094ZFVCJ+jORmU8Er/JBLvuP6L/nI7X1HmJJJVVx1dqYc+2HjYCV6uTKimkWZa8VbEkB5ROY7kxrlu86ILBiS6jgLUgQm+ChnKQjRedXpZUSmx2KrYe/4FugQhjFHtew0RUanS77d/ZFaStz48OeZjnGUuSEFPCTGCQBfBGzBE1/VWaTqxfO3htkTodUg7He3+2ln/KDxHqW0QH48wv3BnPSVUb8tzbWnmMO9E57sqwtDjqfA9Z1LxC98Z+DMf8IeiNKkRXn+MbFOnCWODHblwMwiAj6AHalbzWSg00NU9XIe67P1zl48Y/fK31UyX+LaYLenodLhmyxhSCzepmBwZ9uxsOiXVaRs43GCh1l9QPOoVg5Rm9qngsrQUOqNUSqv1mr9c2Lk5hlfPOLA++CTnSAm8PLy8yh9LS870giNecLnAr6mz5A8B+Wruw6738jkvsUw+sq+21B9eDR0GRbTgHKOhjau/M+dUDVCWuqTsjGfNA4uFtEv4d2u8oJ3T+72fkq1YR0CeqBfuOMpKtSvqr8/8PUY5deUSBueFTJ+HBCuAer2aWi1Q0AJKFtQgzO8RC7nsF3kUIJ266HKoQDfQtF71arkcSgofiFhBgBwIY6ShYim4PHLtIE
    AWS_SECRET_ACCESS_KEY: AgAs2uhiwQ7kiHalsggApqP03xMzz8LCuvndeQylhtdhWmuBdJd+3NjECJm/3S3A0laENHinSk0dsjvAqJMO0vgORz2tAkVXhxPVX6Mo1oJsItObaXzNPCnHymcwwj5mjF+Z+FgaGtKTJBpVwFJVKIf+9HxOGDsNiKk8V5DCucRiTTz0BixEQ/xd3OG/DX4/K3+1Bi82D6HtySKgwScaE49C6/KKGPyfVWKPi5rNta+mUnPP2SWJXn+dmSdpPIbLyg8q8nYp5trm9lLtLQLZKjF/fKfWRGIcOVxw0J7xu+ggqteN0Tykhvj5gmIjYU/89+rW1VzAURLMJDQztn0N9mFXFefgMxNz9j465ph6vpumhfopfSNJSk7KNxhriQpCoeSFkx+hFMyRFU1bQ8CZ4yZ97OVuUndWP1OrAKaYuqCPo/V4ft7dQtE2zCFvf+T3HtPcMpeFLbW0/XpgsPPTot9TS7is7epjtNWieCGzzz6i0K2165xgQDXQo89BvFFyOT0gz9l/NdGO7FL38fQNVphIkQQrhWUbhmU9B0e6RrWH60irVwfPB7IdsFffmCivlf3AmpvCR6mR2gqjjKPZlsN/Z7sl3kAZZ9ggikkdxv/DtJJa5Jf/zB5Wm5SGrvgYoYbuUiU+Q5GPN/Z7MOf8+KvrtiqxZFkzCLi3BXL1C3Rjsm8bc6rMml7exlbaNsjD5+ybInRtIJ0QdA8O6CuJj/JDjlFZJXGCeyXUi9HxV3U4
  template:
    metadata:
      name: logical-backup-s3
      namespace: immich
