---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-oidc
  namespace: immich
spec:
  encryptedData:
    client-id: AgC8tdd9lKKwKl2v8Zzq4hKX25gnthIYYVddedJI4kjJysnJU8C/3WZoWhfGiplaftkF7oEuZyl0zKoBX6cISLkQbreXqDGGZAsmqS1C4p+8BMl5XzvF4bOQQoQUFBQ067FlEoapyJMaFaGkUs9zOJzirlXmNpfn0Z19fCyV281ue2+XZWMcNcRX9RjI2/8tjp8ZQ7nIWo8aszWdaGth3RRKJAWSsB0qNawbjDfX9yDgBf11HogZCI0aIuEhfwEiTbQuudyLL54Pi9Xj6E/C6Ku96SBqLuYHt/4h/7PORFuRj2UnyqxoTcvkCzvDfq3vef5KmOq0AEz4t3k2d9zI4a7Jl9DAV/5MvH1RcdrFAP7zq+M484LOP9DV5lCZ6x8pB1vLMPpzJZ3lb8U61AFnFxx18rPNGHN1tgRySZGVGePH38pinQYCeE9UFQb4x7uH/zEhLhOi5fqJvNCzGsvG/nnJKrS8Xnin7K2NGFliWY9qxhVj8pMgfLMKZGnIRruYglRK2va+QMJh+5KK9g05jblB1K3LMnttaLfRExnxCUYVQuxlR+rBAYyTFWOUeNgafgha6lrHYhrRFU6y+d3IA6MrEel5szMBDEcCGhATzFlK+EINaozgwlPnljmvNSG7+shqc16aR3gRAvBa0mfywt8X8mdAL+FGedz25B89Nzhz64gBjxB4om2mPOboK0mkY1Lxi6akVR4=
    client-secret: AgA7LdDauQhzMx57FnK83g6be5uqRWuCWbE6bA/YzfnbeplAkKOmlv5TWu6InMl706YduOmnliMJ5lJ2S/mgGxsamRywqFEJR6r6kvAwqZBToG8Q3+XHCr3982ljQWY08kgtxf96J3/unNy+Chr1hrcbGUJSCCQfLxCy6ssQdPBxkPyezBQSUQESXvE24vLzlEO83PI3FOGvSdt6Xm/rb2c9MD/D8H+iWeA7p0KL8zNHJRby35dG3HdNAKK2toz5aPbEIIgT4dRUyBF33MbK145VT9Hiwb3P9AjQS0bUCrQmLNsPLYgYI/pv2j7DQpjfbeh3vcQBxhIXTlCkAhVjcKLvQaogerWWI4ETnohj5StYav1ymDV4mx0tMEQFd4c3sLq68m8ySBhIACJx/IDoPsJf3DpmZcLJ307cWTJG+mPo8Ja+kxXT5I9N7VOsQJ+zyd5lDOR2ld3Rn+pwLMVXACv80dsz+x+I9Qt6C3or1zcdvAwtopq1CmNyNd91O/Ngp8xbqkTuHna4bSTonQsbHMtfS6+PnG2qT03tZfdyYB/SZo8ou70UwJ2dbPDKhT8aOHNHuPLJzrWPZI+h49Nt3Rox4ZsdUgCtTvvxGl+RbdAmJcQcVHzwwZdfctp3gRyYc0NHuWgIhuh5XFthq9v04kvG2LgSJaNNYdwOEsbPGNewHpIHx+lARNW3EkbiBeWv6rumSNbFk40eVwwq5aVhchlwMvQUFY+wZ3dwwCfGBKuv/iWjdAMUdInbOfgE
  template:
    metadata:
      name: immich-oidc
      namespace: immich
