---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gramps-b2
  namespace: gramps
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBKpPSKjLyxCmdWj1BAVQhA3tQHzXWTfhnU2Co2kCArd+VIGFd/KB4oDIyqQStD30XBHDGNqdmwhemfJNbLYZxnxiuWKAcuafR/MGhCnU8Lt6QLjedAGTL5goXXu+f/KgxXM5jenLOJzWinEXvnq25UtQ+Tv6mz1i02iM0e6H/93O0+p5iM+Uz35ueNWZHd9NxJa6zo/dHkFg7ZaqG2+Ua04Uigp8EpW9kT59ifxD0m8TRAok01tbihziu5YYoKZG0Ds285M/IP//KUrN6IBO0I1Q/wYiLQOy+vPpKARtIxuKrFa2UhERJUfSl7E+p1bBYWIbuO8GP7PRbVvWpu+jR4uc4AJH13w2XZYBqUX7GsMAs1ZP8NBeW6zMK/97MGEGDr3JqT3IL3m7Pxo5U5sEcREVkkKgvOpAztRFnIAS0/U5ACI4pLlkY0bMwkmKbYxSJh6Skj0pgCf64dfe76dxFFy1SzdVgViQ0wziI9FiiEx3zeOSN1+jeETxEF5X9etvwr/LwXeikBj29foRC0J9piKA9BlgO02enlfByoCXgS3rXDHWzkAtM2VE1ZZ/CHRPto6niJ5VR+KkUe5RT4+1z2rJVJeVJgoWXvjVu40DXBB7c3UCfxSSbmdS1F6vzHvEYGnnWwxDB2tmM26hZQWCA2i+U1o43gL8M74ZYJ1XSPoo92GnRPEdxtlU2cSF+fCOBiBasSirS6X4Ae8I/7IUmmx9MzVIk697Mk
    AWS_SECRET_ACCESS_KEY: AgAGZQK0yf21T/oES2ye9rV+rui3L2MDqzsE2XCQqSrSLSFYvS/C7ZP3761YZVUB7WpJDWI4WoYbGmPpoIxRUMSa9pgNU9qBAT03jziKzXVp3Na3PGCBT/9ZE3IX3nKs+fHaYHhs0QrCYxYP0t2Nx+iudyM4foSKbEjUvFmJNCFoi5xfFhe/r/+HBNmzJZ/ES/oqzK6nD0m5cilNTHGHzGVFh6ABicfA730nYe25LJMheHohfa3XFzNMuKZqw/2N0G/kZanaFA5R7duwoAF15KcGVRkGYt6+DaDJSH45n4SfsyxMzAY2GPSatU7kJFCY3w/WFGDbUfrhvobmGPOmCd4jSF9VrSHYXy+sbr8IeVvPEH/qAGn6GJdY8LD7SLYudK3nMTc93K+AseJJ5ihibewy8rZuB3vlrdCN4/Hm7CDcmxr+8mRHxaNR4R1qbbKokTVu9SyQnuZRFIpr58FbA+OvirUAZonYcumzTmnEoBIZqmQMwUArHQNocr+QdAaUgo2LYZ+9Ji+dgWjVzzFdVBUqn9YTsDWnVMlnBSyNY+q/cxYgqyld1KRZqZM85S6C87g8iruQg1TWl5QHfKhfJ+IIoeZuMHPZZLvMJpy4amulyFuamiiEYqkDnK4YZgMMQ2XCiWXgmu+3j9rsctHg4wzP92LnbDcB7zBCRYSQ11f1w9NN0Qv3e3reDjINwxME2tS2sXjOqr0Tmd2JEihuC4jbN1jwr/Lu7SPU53Q8L3kN
  template:
    metadata:
      name: gramps-b2
      namespace: gramps
