---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gramps
resources:
  - namespace.yaml
  - logical-backup-s3.yaml
  - oidc.yaml
  - psql.yaml
  - b2.yaml
  - config.yaml
  - frontend-config.yaml
  - pvc.yaml
  - valkey.yaml
  - grampsweb.yaml
  - ingress.yaml
