---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: gramps
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCTcbip14MmgmStdnad5791hpyz7v3CZt0YAdRoEdoX0MSnZRiCM4YalTF5mrQJ46mWhtKDRlRCSozPKx8oKN39kC1t/0wW8Dhd/lTjbMGMOqWXau7rp1DC/Lrwjx7B0t5aCR9/orHcqfXT7XrhaReiCwOCc40Wd842U4A+AgSFn7tGuFy3iYdsYjfHDzdUzxRNA+N4kgMDcekZ0CI7nyC2WAznJn2o+VUePG0vChuBtl3ctupVJ5d4M+S+94a5Z+CT1cR3R7Y5g14QEIJCKUwqEkKoilWz493pVg5CuvcCVrJV4k+xTIrjmDrGoVX3dHnvrEai/hNcpFUKd7VkHwSbsFwQEolGAr6p4lqiu3Drf+VR7ozmyC5QDNm7+HxyUesYpWbmBm8RyQ9e/WjQY3nRTPuKjOBqxuJ0LemXgn1cuLCcPJIm03e0kbgtWMe5bOOKAD3W9r2vvd+hY0QRR39ndej8fQO1oRJvL8a8F9ILChRqpbyLzdTzeRm77IY8KWtIKgwsx9VosO1y8EQZ/zFYJtFwaUCQzubcjiWXaQ+SJwr8LbTP/QzWWQDM3720nCw4DdQp1LjYHBmtTpVE1F18PIZ5jUUpoqKnGFiW0zrncBxkLT1IDX6FFhky9D7/BfD6CndEVQ/IYy1jabUCUy8HUvfAee6wqdQuUIqN2AzV+HLJa3MRXNrExKpLKSLxXyIAjAgfEDyMb2qgUKNB+BYuf1PuZ8uhpXoT
    AWS_SECRET_ACCESS_KEY: AgAo+sg1yXUzg+Gka6xmBPM6I5CBksOOiQVJe/2y6d4aGoAQx3GU/N4L2ecxzngjyvnNIfdmNLHQQWne7TmBR91m9cyoK8ALIfCyxddh/qJKoy6I16et197gCg3ge3muorC9rJZBY2oEDhoj6d74bQQD0mHdDwP+NkYhXLS47Gytp6OlmsQZ4D38pNjB95A0JbqO3L8/6rMwLmXYoTE7aNI2IF53GIYQUv7btOSZHVg8hxBDTtQOZdOJK1t+uRjcEp0ePrWaawUOxtDsdruumsLPAev3rMHo/JyMuJpcbv6S8uo6Lb4iMct00/TfOm3ODHRoN7unNQgKCDboy28icobA3hpEDP39qA0L/YFMygaHXFzJOB59h+RxnVKw8R4UKc9c/mkO5RERs9JOZr6wR+Hl0ZzFdYsxgqo6ARfz5QpSv5Ue/2I6xRWgAP6zcj6uXBu5VLNGfKX2B26XtQlz3oRL+duK1weFAHIYZSYuI3Qqcq5EkXQ9HNvM6OyPLCoviXhBqOscPOOhOFMfd06bqTttPpprP6eiatx4Kf983yOgjCJwzqR8thEOUhywv9l/YjodUUOxoCbXqY4S8ZoV54Gbs2dXp4Za/AodMMcvXO2Hn9muAYQqxcZ3rzZ9h8kNcoXxtxYhXjw9gVXCvbTkmCVKUL5EwbF5uxXENPKzYApREuz+FAj8yBd7KXfiNu3iXsivWTrUOP6e62wigHRC8qaRZRFEL4xLu5e5cXbiyBx1
  template:
    metadata:
      name: logical-backup-s3
      namespace: gramps
