---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gramps-mcp
  namespace: gramps
spec:
  encryptedData:
    GRAMPS_PASSWORD: AgAcX4VnHUlthJDPhArpQ1ZPfGEPqRELwZd8+/yxbN32zmJGgmR9HbMl3qO1iM7pmN/iXY9MmXK8G4JyUZear3PDid0TJD2KhRN2AaMnD3dxlR2LUSDmkHtveAEJ7kSWn08EZCvmS3TPS1R4t7qyh/GU5qwjSma1cLrWAuWfFkKkxKtpE8H8vR4o2awi5QBeBpr6en2rhGuG1rPIYWHOS5z3jG7HAPJ13V7THKxBv1BfTr+50DquNiAsQpZLAgAsYOCSJefIKh6Pj2FIQlKnb7cFFHsi3oQ8ZrFKnId9KGXXpjxpuPVo7k1V77HmGy6gM6zHTwsRY9O80gW4JwuUJzqf6F+z9OQRjvN+8SYqQTvThfvPLtOFWSh8tIyxeXtHVllIOe5naiowW8bbUVMJJlkMqz88nXdkBhBhAIDblQ+WwRkPRxpKshDgrKkXnldSfuk1SqcEi8Qi5IWCTrdpx3hefiR2SfNeLJfsyVM/r7xbBXb3kcWUwl9A6rh/XvNcXAkLbutn7+unYlFTbF5tXC+bFYxBTPrAM0Iu/hOe6sXCDEEUxqr56BAzKWqvODjl7aSwmLYpPwiWOjCOKh/OedfcyBjAnaw8x/rhqzgI/91E/tNflyQfgbrR1L0egTup/eH7GVG8PDkjnBY25SM4+oNo2+u4tlxNs6e0McXHxg+TiFtnN/joR/vTSookhImm0q3mDSr4LZoi15kQbg3dMNMhRnLi3dRTi24pHb9pES3yMg==
    MCP_AUTH_TOKEN: AgCWsqVQx7nNJ+9xrDLa9kQMoDgML/hQeSp1IINJhYT95NK1SK9maNuZTlzQXr5ds/pggwqCA/Us4AFcNm3MozZU434vNgTY3xmqbOd4FaWexgXHVoka18XYIc5tBMQzHtoptB80dXjzDdQZe1NWHXdYOmNnGcvH/TYa/C0fHuoOg3MS3hqQePWiSfrckVLJS7lM0AkTwZhzG3gXbuqhxQ8KSHPe6q38PbOQjcH9mxUExN7Nyf036ve45kBaAjXqBrBdKG/k3G+DxnF6mJyyatTTRXNy95f0znnvtvpjOv6ADJdr659Qtnc8muW6RnKcgGJ6vP95JRj8ZPvG5t+VgWt5rE3WQTPmT3SYbLMS43vjQganzrtZCUzvdTG/QxAAIsflf9h71fDCG6yBhCnxHCo0DnIFVdV3oicKRSp/k3s21dNZeQfXBtBfq9wqpAUYQlCBLtI9VWA/eTMnoKIKWISrK9xO7IvVYTJ7ZqP51Ry8Ti3/D2VVP4KTUPkQb2YjlxO3cyUrrSwThJsCyqqjObTP3yyctIBOGFxGmPNZwvsa1lg2X8uu+iXuNyanaxnJfztXvqJt8JsI0PbUjfQYGIq8sgVaAnClBBZPKcFO4Y6HvKlQhB1r66GJt/XpNRJAqA63Mui97W9AwId7TYkvQua9VJvoegK2sMvhTd+qgY686xNQISjU5E9qKJf8FZz/QUG90EoqiP8f6fh/hB5AJYels34SH/LOBGBgZwHcYNEJ7VnBFcY2IK93HnXns1zj1cqkZKXyATHPQRgIJxqm2CPB
  template:
    metadata:
      name: gramps-mcp
      namespace: gramps
