"""Config revision: one hash over everything git ships to HA's /config.

The pre-commit hook writes it into packages/config_revision.yaml as a template
sensor. The ha-reload hook reloads HA until sensor.ha_config_revision shows it,
and `hactl health` compares it with the repo to detect drift.
"""
import hashlib
import re
from pathlib import Path

from hactl import output, paths

SOURCES = ("packages", "dashboards", "themes")
REVISION_FILE = Path("packages") / "config_revision.yaml"
_STATE = re.compile(r'^\s*state:\s*"([0-9a-f]{12})"', re.M)

TEMPLATE = """\
# GENERATED by pre-commit (hactl revision --write). Do not edit.
# A hash of packages/, dashboards/ and themes/. The ha-reload PostSync hook
# reloads Home Assistant until sensor.ha_config_revision shows this value, and
# `hactl health` compares it with the repo to detect drift.
template:
  - sensor:
      - name: HA Config Revision
        unique_id: ha_config_revision
        icon: mdi:source-commit
        state: "{rev}"
"""


def compute(ha_dir: Path = paths.HA_DIR) -> str:
    h = hashlib.sha256()
    for sub in SOURCES:
        for f in sorted((ha_dir / sub).glob("*.yaml")):
            relpath = f.relative_to(ha_dir)
            if relpath == REVISION_FILE:
                continue
            h.update(str(relpath).encode() + b"\0" + f.read_bytes() + b"\0")
    return h.hexdigest()[:12]


def render(rev: str) -> str:
    return TEMPLATE.format(rev=rev)


def parse(text: str):
    m = _STATE.search(text)
    return m.group(1) if m else None


def is_current(ha_dir: Path = paths.HA_DIR) -> bool:
    f = ha_dir / REVISION_FILE
    return f.exists() and f.read_text() == render(compute(ha_dir))


def write(ha_dir: Path = paths.HA_DIR) -> bool:
    """Write the revision file. Returns True when it changed."""
    if is_current(ha_dir):
        return False
    (ha_dir / REVISION_FILE).write_text(render(compute(ha_dir)))
    return True


def _run(args) -> int:
    if args.write:
        if write():
            print(f"hactl: updated {REVISION_FILE} ({compute()}); `git add` it and commit again")
            return 1
        return 0
    if args.check:
        if not is_current():
            print(f"hactl: {REVISION_FILE} is stale; run `hactl revision --write`")
            return 1
        return 0
    rev = compute()
    output.emit(args, {"revision": rev}, rev)
    return 0


def register(sub) -> None:
    p = sub.add_parser("revision", parents=[output.COMMON], help="config revision hash (pre-commit runs --write)")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true", help="update packages/config_revision.yaml; exit 1 if it changed")
    g.add_argument("--check", action="store_true", help="exit 1 if packages/config_revision.yaml is stale")
    p.set_defaults(func=_run)
