---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realliance-ingress
  labels:
    service: web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: realliance-net-set-csp@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: realliance.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-realliance
  labels:
    service: web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: realliance-net-set-csp@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: www.realliance.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home
                port:
                  number: 80
