---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pat
  namespace: registry
spec:
  encryptedData:
    password:
      AgBl0WKOf8yueluyfwk2EfyPZnxpTDPMRPdubnaoAEDC+3tLImZuNZdrfn+QfE/VO2zlTlZTKeP778W1U6nKmDpeLz/pezOsTr05dEa9JgWLDLO+DaAH2WV6TDKFwZT52ShUtuq3D9sSMQCldPQNMR69cfTt+FQDXlTONzcpzM8ZOIuE3Sq84ZeahtHF+x/Jbki5GSqfG4oUvmFBcROfLH2NaAgJrnaAAWZWOirL1DR284riu41zhNTTTC0s2TT6uUlYmsqDQgvHeFnq3phh0Lquk4W5y6VkEvSgMOz5nJxH5krZTCZa6vWlu9pWYGQhAu0n5RRtC0BYEEF5vZsdnVmiS7TK2ra+6MAgOlHwcDh9evYbNq+tGDM1wUGlYWJK+BYGf420KeEwxmX3+wkKbMEeCYW5FFnDVeUsPGgkmOvqIi2KiiDi0oC+GZHFgCDYJLVYJPMEksSVp9YbaSPyVX13ESwZLAF81zf6HXC6Ux43pgxfM9e2wyic/p65L7tDkkXEH2wNrkpl8EYtR53uYPMj8/Ydi6StOiNn5XTLeAoVF8X+XSPcn+uxA3FbAbckANIKqkRJAhdVxlB4v5sJs29efG9MmrVml4Vif3N9SYsyPkPnn2R5EHJvhNfZMEeYQYXaTzGSfAbDml8DANelFHENsR3sFDreHR/8OK4NNq395/V8kGzeAJ/Ez7tVHfaWs2hKm8xOeNAG3O/hnWvARmFb1aX8GeSBtQUp5UC4342posgIT+I=
    username:
      AgC2XXl8kQU8RwoT91Zs8oji1KBhUFy6oEET/ZmcyHFWGYMK3QolM9OieKzmqmT4Cys+B2nLPLHadt0gEQO4I2nj2czi/SBSYUdc45xr7lYq+NXFoxsIMLcGZy/lQep0iWJv8P3bwuNmTd9A+KZ0U4LTnJQBGGiikPFjM0C48HAvqnOh/mdB7UWkLJBvV99T0FcZI8IYVU1vU5Ds73751f3g0jBUQeltrn3khTQl3JQGefQQOcl943N84mcTRiQeWXWHybIFhdLDNbp6cEbr+8eBe3BSyzmnTuRa9oz9h66cd79jO++paZECC59u3yPqBHd0ZCBTzJiRzQyFQmYqUnGpImd0he0zi7ZJpRu468j/rsZY7R6cwmtrqZW/jlmmas5MGbdwnTQ+NWbgH1mt5UnTVA4sLGDnWWsT1BNvjTW+kubaXQw+0xUjRHlFcwK/JuyOO8Z3ofFFe4RdHc0zKIZ4UV3Baz8S6RNWJV/JK2aNy4jWizFCTr6OZDaNLInCqJfflUzCP6t/ilHekusU/FIkbHbbnHbwBCpm0Ifa+uIelQlhThMvm/k0ntmIeMzeGEtP+5C2cbPsf3+giE9XvJ+Njjma/yuagSP7PAxPQElP6Hs8SEobbN2cLZmwIEtAyRRfDMMkdt4lgoZkGfceeK/7TgsKF7bWueFW2+qWNmnbZjsq6S1ez7cW825MeFF3ixPy8kqfzQ8=
  template:
    metadata:
      name: dockerhub-pat
      namespace: registry
    type: Opaque
