---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gonic
spec:
  ingressClassName: traefik
  rules:
    - host: music.chrismiller.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gonic
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gonic-webdav
spec:
  ingressClassName: traefik
  rules:
    - host: dav.music.chrismiller.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gonic
                port:
                  number: 8080
