#!/usr/bin/env bash
# Derive cluster/gramps/new-user-emails.secret.yaml from the family allowlist.
#
# There is ONE list of record -- cluster/oauth2-proxy/emails-family.secret.yaml --
# feeding four mounts: the two oauth2-proxy family tiers, the MCP forward-auth
# validator, and (in another namespace) Gramps Web, which needs it to decide
# which first-time OIDC login is created as an editor rather than disabled.
#
# A Secret cannot be mounted across namespaces, so the gramps copy has to exist
# as its own object. It does NOT have to be maintained by hand: this regenerates
# it, so an address is typed once and the two cannot drift. Run by pre-commit,
# formatter-style -- if it rewrites the file the commit stops so you can reseal
# and re-add.
#
# Why the copy exists at all, rather than trusting the edge gate: Dex brokers
# Google and Microsoft and authenticates anybody, so if the auth middleware ever
# came off /api/oidc, "editor account for whoever asked" would be the failure.
# That is how the MCP endpoint was world-readable for a day on 2026-09-26.
#
# Both files are git-crypt encrypted at rest and cleartext in the working tree,
# so this only works where the key is unlocked. It never prints an address.
set -uo pipefail

source_file=cluster/oauth2-proxy/emails-family.secret.yaml
target=cluster/gramps/new-user-emails.secret.yaml
sealed=cluster/gramps/new-user-emails.yaml

if [ ! -f "$source_file" ]; then
  echo "mirror-family-list: $source_file is missing." >&2
  exit 1
fi

# The block scalar under `emails: |`, minus comments and blank lines, and
# UNINDENTED -- the indent is re-added on output below. Stripping it is what
# keeps this agreeing with yamlfmt, which normalises a block scalar to four
# spaces: emit the source's indent as well as our own and yamlfmt reformats the
# generated file, which this would then regenerate, forever.
addresses_of() {
  [ -f "$1" ] || return 0
  awk '/^  emails: \|/{found=1;next} found && /^[^[:space:]]/{exit} found' "$1" \
    | sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | grep -E '[^[:space:]]'
}

addresses=$(addresses_of "$source_file")

# Fail rather than write an empty list: that would silently turn off
# auto-promotion (safe, but baffling), and the likeliest cause is a locked
# git-crypt, where the "list" is ciphertext and there is nothing to mirror.
if [ -z "$addresses" ]; then
  echo "mirror-family-list: no addresses found in $source_file." >&2
  echo "     If this is a fresh clone, unlock git-crypt first: git-crypt unlock" >&2
  exit 1
fi

# Whether the ADDRESSES changed, as opposed to this file's own comments. Only
# the former needs a reseal: the SealedSecret encrypts stringData, not comments.
[ "$addresses" = "$(addresses_of "$target")" ] && same_addresses=1 || same_addresses=0

tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
{
  cat <<'HEADER'
---
# GENERATED by scripts/mirror-family-list.sh -- DO NOT EDIT.
#
# Add or remove a relative in cluster/oauth2-proxy/emails-family.secret.yaml,
# the single list of record; pre-commit regenerates this file, and `./sign.sh`
# then reseals it. Editing this copy directly is pointless: the hook reverts it.
#
# It exists as its own object only because a Secret cannot be mounted across
# namespaces. Gramps Web reads it to decide which first-time OIDC login is
# created as an editor rather than landing disabled -- see OIDC_NEW_USER_ROLE in
# config.yaml and images/grampsweb/oidc-new-user-role.patch -- and it is a
# second, independent check rather than a restatement of the edge gate: Dex
# authenticates anybody with a Google or Microsoft account, so if the auth
# middleware ever came off /api/oidc, granting editor to whoever asked would be
# the failure mode. That is how the MCP endpoint was world-readable for a day on
# 2026-09-26.
apiVersion: v1
kind: Secret
metadata:
  name: gramps-new-user-emails
  namespace: gramps
type: Opaque
stringData:
  emails: |
HEADER
  printf '%s\n' "$addresses" | sed 's/^/    /'
} > "$tmp"

if [ -f "$target" ] && cmp -s "$tmp" "$target"; then
  exit 0
fi

cp "$tmp" "$target"

if [ "$same_addresses" = 1 ]; then
  echo "mirror-family-list: refreshed $target (comments only -- the addresses are unchanged)." >&2
  echo "     No reseal needed; just stage it:  git add $target" >&2
  exit 1
fi

# sign.sh skips a secret whose sealed sibling already exists, so the stale one
# has to go or the new address would never reach the cluster.
rm -f "$sealed"
echo "mirror-family-list: regenerated $target from $source_file." >&2
echo "     Now reseal and stage it:  KUBECONFIG=/tmp/galaxy-kubeconfig ./sign.sh" >&2
echo "     then  git add $target $sealed" >&2
exit 1
