---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chrismillerxyz
  namespace: chrismillerxyz
  labels:
    service: web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: chrismillerxyz-cors@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: chrismiller.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysite
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-chrismillerxyz
  namespace: chrismillerxyz
  labels:
    service: web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: chrismillerxyz-cors@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: www.chrismiller.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysite
                port:
                  number: 80
