---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: chrismillerxyz
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgALnqg+LKY0vsbaAO4PHhpL0DcDMT4JMNNEJ6FV/ouV+Pdvale57hRZabglz6wiWcsA0l5fjVOVlVUQA4VwjBC+21K7rpkouzI62IgMD8vs5y8Txius3FFkDeLKry+5UPska/giII3Tcqr0hNHzDIJ4stGNBfkcufWib/I4Avavkh/YWkc1L0gNq9gzljDHNHwl2LjP4aJbuUnR37WGl2kypcVRBX9SZaaxwyAencWYXhMxBsExjL6SKWx6qaaPgG+9Yr9nvUjobEVbWgJQMeIfjUf4uwNJSDWBhXBaJ43ffBlayhHv/GcIeX3pyNOq1ZjTXcUY5SNzK+7opxikDzdtjrJC+02Iao6NDPMFXL7z0Ye1KMYHyTNI6mZdhrZjVmuthR1jSBat+ZB6tFUiu5vl720lLZ/o4y1oiB/7FeoUrMXq+GqIIUZMJKf3suPFH1ieCLjmoocvHTnJl7988sghkZiPTjn+QI3J+AysC4QG5qK3ai0ayIWF9Kn7rhfPmUAVhgvvhjoplMXcbJWC9K4Gtd5noXTiU1EszAjy2C33UGXV1MKdBgWCJTgapptMDSy75CqHCjYwL/1BSrO3RaTjF16r9lBsxyxsu43HCbiRvj3xF4P0AKILvoz1HzIZldWUmRBGNMIR9edFArjM1aCBZik+aP5GVtSAS6guF/N/7xZo3eVYi1qx9gPVfl4n/L6QOV7p/ArliGG8qflKg6iv/hHTL4ucxJ2u
    AWS_SECRET_ACCESS_KEY: AgA63NbRYwFQiucMkaSThH5gLqEVdNM8M857Wy22bzelpVA4O/8EmgL4hdV4SALzXQLUkaUiD00hpLnf0sTdut3t/WxDvEoDP4kZgf4TMpb4/VyQtSZKrqFyZ286xJARqrWF82HkADwfcHTkYsTklkhMyx9JojEF+Bo9b04FTb3NYg4+Dx8f9HLB2aDNLfla9ats9W7b3FyL8F6uVPBPf16O1iqsLmWXMPn9Pwix99wuirHxaGfmgQYMi4tATs8nWslT78CHa7TKtssQWAE0Tc7gzXotP5dSmvUXJDsqF/oIM17qiObMShzbIp/xAAquMlInMWA/DFOduHTu4Bupwgl1MTS0B5EoZJYpyj5U1qfv9s6Iy5FZ5oMJ7RWgaG2BJTmBxqUo+tffHPtT4fRuMGSCn5wIPc05hBFlaxtIfR5D7uQxz0gj33B050RjHWXv+YzCrmEQzV/dPn0PvzCF/YweDFW3MyrzqOdmw9pfJsc3YOAg10rZRQKJMaHD3/t494s6BxLXcZQTXdFfGGqKQ3gHFgF0EFaRI3PR41/wj1tmfSwmHOmd/EmuRvyWZQfnqkrBgYMNt9c1Py389TFTcWnscsBUsE+DMYm4i7qWrLxTtwCmN1yDI4caEhTN9o19PXbjMR5IhGlIhzm+JyQCFmAipy9+i1GTPTvssyqdI937eZ0hogbmRxPfIOZ6VAhJGyX3yhI9NWXdJ031Nw0CHDsaibw2r8OKVSxGO0wCiGXy
  template:
    metadata:
      name: logical-backup-s3
      namespace: chrismillerxyz
