---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: media
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAIR52jpUdfQm90AlknZlg0Y2eDGioIsXJZ21NikHfTHpHPzniVFwEvcFL4IP87S/X1VG2k+O2RexhS4oBt+/HoujNQFmNoBKrZpXT8akd4/Ua7OJpXoUXaQ2Nd150cdHa/rjWYponchDutinSuftEuxjXs3GkZN+/rFF/s78bHuyJw3yDlinhLhxmu9rFoelOPaMoluEDE5zqZccjBt5S+D3xR8Pswk9ZT/8TzE+C2uZthCq38+dWZVReUmxfXuoVmmileREzk9JLQiTT/p7QhSEDRK7C+mM4vwI08ePAmLUdG+XZH/TqSEvAU2moN4yew7wWTFql9sB19w4a9NNPhady113IlLlWczLUWHET4vWhPwlryMawTX8Mq7kdeI9YYmtqXN/dEHrSmZ5HJIgg5+gx1otpqosm9T8A91lcbmkIuYwMBau1M/s4IElPu2z0VoYAHwbiEdQ3jJ15AyG20w0TyiL3UZooNctO8JZnNlnNO8GX65fxPOMulbu8qx3zzKYffNw4QSptP7kIBOu1QLfDmNh+T9Du84yQ32QIb5CT7SpytnhuXaKjFS0nPtJdGKvY1i9HE1P557PTXCmLx0CWihfdCzLGU6MD6ly1DUu95l0HSMUHYzuCrUQwwsqFyUxQIXkU8//ctNi1XG+vl7Jv5lbzmkNwEorUqQ4gkwo3+0LPCiEwlVlUVNjM5hopt/ugT49vZnVgBHR6OY5ENc35FihtlXEow
    AWS_SECRET_ACCESS_KEY: AgA6hUDwLqJm1CdjArlpJw/lluDZlEcikt0s+uWpPIkuYqTLRf7sXksF4W02ldGj7JQBggatNvLugpKPzaRUANGegcp9bBqFfttF2cObBRoPuHugZSPxCa7ijpq7bB//zPxjZj8FDvGvd0vtNXhUf7d31z7cKxOYG9URiFA3ZGfAQ5IKPeNo5/M2YZDZ4UfGM+mX9YNFn5ziEhHvVAx/27v18g3I1lOD56yYU4XvHjk2QyVjAXcx8FeQXz4ZpvnOicQmC6TGYxcy8vd+/cspbG8BwhXcp4GnYYI3snTNl+XYvPiBZNIkrIVkuN6Tl0Nr3cjZkGrDMTtYZIkqHIf07I8kdKOtGFYus25CEC8xCPYaYFsMK5AqfKoLJbZaljmI9GuhaBThnaSx5K3kfGj1mT9ktrJFGNn8xHBdOQTA+JXVFo9OAnr2rGpcxCkiZbSoGI8i4BMtlQbVUybE74xplkK2G0VBBP4HMHuxhCSx2gE+SKkIWkWyBDPyp0PrJP/VN2Za+4ZPCxv85EzmgwVKkULqiouWDdOyXGZg9uJc8UlDivVhBt2tBRr5TjWM/B0T8BhThYgBhccQ1F6y/RzM/066Bauks6r45iPj7NEjOpxavzD4LLzpnzPL8VlTcU6iJqeX5bKXZhvaS5SA3CMki/htFZdfk5xF6y66Bag+ayJ+JsfIY+Q/IPmcGE3Hg02C5RcN5ZfkC1+R6dukcicaBOzgRs6XV3YGQ20kbPahljTE
  template:
    metadata:
      name: logical-backup-s3
      namespace: media
