---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - logical-backup-s3.yaml
  - psql.yaml
  - postgres-podmonitor.yaml
  - session-key.yaml
  - redis.yaml
