---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logical-backup-s3
  namespace: authentik
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgChdsm3Miq5kwOLLxcCFNn16Hh/53ps9Ds7sHUOxWGPZL+qli3qM/3/JIEP4U+9mI6P1Ugk9aK3u27qLTlG6eA0rOmuhJmwp5G2xbEJeVtgOicm3H921QjUQCsyWMCywEy+5xJ47KZR25UZWj87Zn4QWPNYdcZuOJg1LbMHecbz6dWYCNtxA0oHSP37UparoDs3+1KkVDTbqnKOKxmZtl1j64dExfS4iS2Uizry1CfE5tAAH1sX5QoPLDEadN1X/tar/Ec+vjjdkqkBUTYWKCAPpKiiEEjWHEEbHPqGLunb4c/390Fs72Diw1kn/M7vKEVvQeNHWc4ARMbzgczn0ARouQY5pgJEAsY49G/VsCw4woVZtySTlurY91wvAtI1jW7zT8Zx7TTILFlphwTunuZHfOtwLxDuBD+n1fO6czquNfqeqK1mUUAKXMQLVtNLnoaIRXffM9tH78u2ud+td6dnbfpSN418zFzEgBMKvArhjqCb8RVse1UmveTRpwR7eNFWifCf/QfesR8vYumucVLGEiGQObL8udFsOPW1+fCKelYnOOp6jTRZopoUX+6rXDvwSbuJCPeVtilUpMJ1/R5tMPKOK8ZsqmWGi5RqHqv7emf9Zph9f6SPL7EvOC6BW5LVNELNsBL+5wBdlHNq6zuVKHTJ96aQA/+SZt6+Y1Y/eaQnQxVoyiKAihScCEZ/fczsUT+pOuzP/3CJM7SA0ARB6bFs8kmL0X7A
    AWS_SECRET_ACCESS_KEY: AgBkSDiBfTNM91rkY0chDlmUmKgOnZqnOrZ9b7C4c3ou9siHMENQbMPPkUWecOVCSzJf2YyoyHRxLjNNBZE+eulxkiNXUf+XDyED1e5uJg9pC9Kiq0ud25XeyBAcV0bICCIsQZdTQcwoqstI950ho91lQOM4RdSAAr6pPCVYhXDuKbEobPyTZPDrIsqBCwtlh4Pcs+uBd/+C35q2qlwLyQ1ebjB8PV8KKm8s0ytqyrKiBaVHZm44iFzl+I9dJPwm/tfMwhiK/BcqVa60cB/ZoRvZUdun2ViL9Lt2n+LuQmWj9TAON+qPJ44wpezPqmssyeC+sc6C/MRC129I97FrjVeeDnyETT2N3TKgidY4FyORR0Y1kw8xCY7Pg+atnEibaBz6iYqXgke23d7zqnCnb4J+9kKSirCkk+z6qZe32sKmOGzGlSn9ykaiILyBMcksQEiCb5oZvwJBJ6EjieKd7NSseCff6hORzPeiBcDMI5pakR6IRM4ACzKRyMq7g+R0qE8TcDm3uhHzf5+BDLHvvL2kVdnJcxW/ol8RWG3g4KDEbgDVDAfFCfx2R1LmRskWrfR+fDUeWesCiFIOCCCJPd5e83csGoVXGxO965+hOXp52mIKwxVKqf6tvfYH5WaLj8OCYpN9HY7xpM8HE0IY9UeKYZ9y+DM9rdCT5AlLAo/tuu/j4MFtapE93mCSNBc/JCnCrZkUULlp9OPOUrnW7Xr8aiO1bzj+haXmgT5L9Xmj
  template:
    metadata:
      name: logical-backup-s3
      namespace: authentik
